### ISSUE TITLE
stubby: Verify failed : TLS - *Failure* -  (20) "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by gitmirko** [MatthewVance/stubby-docker#1]
Hi,
first of all thank you for providing this setup.
I'm experiencing some troubles:
- the 2 containers don't seem to talk to each other:
```
version: "3"
services:
  stubby:
    image: "mvance/stubby:latest"
    container_name: stubby
    networks:
     - dns
    restart: always
  unbound:
    image: "mvance/unbound:1.8.1-stubby"
    container_name: unbound
    depends_on:
      - "stubby"    
    ports:
     - "MYIP:53:53/udp"
    networks:
     - dns
    restart: always
networks:
  dns:
```

- if I set nslookup to talk directly to stubby I get the following error messages:
```
[12:09:53.321385] STUBBY: 9.9.9.9                                  : Conn opened: TLS - Strict Profile
[12:09:53.522897] STUBBY: 9.9.9.9                                  : Verify failed : TLS - *Failure* -  (20) "unable to get local issuer certificate"
[12:09:53.523007] STUBBY: 9.9.9.9                                  : Conn closed: TLS - *Failure*
[12:09:53.523533] STUBBY: 149.112.112.112                          : Conn opened: TLS - Strict Profile
[12:09:53.523646] STUBBY: 9.9.9.9                                  : Conn closed: TLS - Resps=     0, Timeouts  =     0, Curr_auth = Failed, Keepalive(ms)=     0
[12:09:53.523718] STUBBY: 9.9.9.9                                  : Upstream   : TLS - Resps=     0, Timeouts  =     0, Best_auth = Failed
[12:09:53.523785] STUBBY: 9.9.9.9                                  : Upstream   : TLS - Conns=     0, Conn_fails=     1, Conn_shuts=      0, Backoffs     =     0
[12:09:53.718249] STUBBY: 149.112.112.112                          : Verify failed : TLS - *Failure* -  (20) "unable to get local issuer certificate"
[12:09:53.718392] STUBBY: 149.112.112.112                          : Conn closed: TLS - *Failure*
```
I'm trying to debug this issue for a couple of hours now, but don't seem to find the issue.

Could you please provide some more insight regarding this problems?

Best regards
Mirko

**Comment by MatthewVance** [comment]
Thank you for reporting this. I've experienced a similar issue and have
been needing to resolve it. I can't troubleshoot at the moment, but I
suggest changing the tls_authentication setting in the stubby config to see
if that helps as a temporary workaround.

The cause may be missing certificate store to help with TLS validation. It
should be possible to install or point to the standard one Linux uses. I'm
wondering if it's missing from the Docker image.

The other option to try is setting the tls_pubkey_pinset in the Stubby
config for the upstream provider (Quad9 by default in this image).

Sorry I can't solve at the moment, but hopefully this gives you enough
ideas on what to try.

**Comment by MatthewVance** [comment]
Quick update on this. I haven't been able to solve it yet, but think I'm getting closer. I have it where dig (I never remember the nslookup syntax) works when pointed to the stubby container from inside the unbound container so the two containers are communicating (i.e., `dig @stubby -p 8053 github.com` works).  

I also have the TLS issue resolved. I had to move the `ca-certificates` package outside of `BUILD_DEPS` when compiling stubby so the /etc/ssl/certs directory isn't cleared when uninstalling `BUILD_DEPS`  and then set `tls_ca_path: "/etc/ssl/certs/"` in the `stubby.yml` so it looks at the correct directory (due to how OpenSSL was built, `openssl version -d` was point to the wrong directory).

I think the remaining issue is related to `forward-host`. Best I can tell, that unbound config setting doesn't support the `@port` syntax like `forward-addr` does so the calls to the stubby container result in `SERVFAIL`. 

I'm looking into whether switching stubby to run on port 53 will work so that the non-default port setting isn't needed. I was able to get stubby running on 53 by changing `listen_addresses` in `stubby.yml` and running `setcap cap_net_bind_service=+ep /opt/stubby/bin/stubby` when building the stubby container so it the stubby user (non-root) has rights to use a port below 1024 (setcap requires the libcap2-bin package). For some reason though, forward servers still appears to be failing for unbound.

Tip: For troubleshooting, increase logging. Change the CMD option in stubby's Dockerfile to `CMD ["/opt/stubby/bin/stubby", "-l", "-v 5"]` and the exec command in unbound.sh to `exec /opt/unbound/sbin/unbound -vv -d -d -c /opt/unbound/etc/unbound/unbound.conf`. Next run docker-compose up (without -d option) to watch the logs in the foreground. From a separate SSH session, you can exec into the running container with something `sudo docker exec -ti stubby-docker_unbound_1 /bin/bash`.

**Comment by MatthewVance** [comment]
Quick update. The remaining issue definitely appear to be with `forward-host: stubby` finding the other container. Commenting out `forward-host` and replacing with `forward-addr: 172.26.0.2` (the IP of the stubby container) causes everything to work as it should

You can find the IP of the stubby container via `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' stubby-docker_stubby_1`.

Manually setting the IP of a container isn't ideal so I need to figure out how to get unbound to resolve the name of the other container so it can forward queries to it. I'm not sure why it cannot because pinging stubby from a terminal session inside the unbound container works.

**Comment by MatthewVance** [comment]
See c87fd2b and 572e306 for the changes which resolved this. Quad9 was giving me trouble for some reason so I switched the default to Cloudflare.

**Comment by gitmirko** [comment]
Working as expected now. Thank you Matthew.
