### ISSUE TITLE
Why is root-hints not used in unbound?

### ISSUE THREAD

**Issue by txtsd** [MatthewVance/stubby-docker#15]
Why isn't `root-hints: "/etc/unbound/root.hints"` used in unbound.conf?

**Comment by MatthewVance** [comment]
By default a list of builtin root hints is used by Unbound. Providing your own file is supported for Unbound in the event you
need to provide a more up-to-date list. If the package stays updated, that shouldn't be necessary. 

Plus, Unbound is basically a local cache in this setup and Stubby is doing most of the work. Moreover, the default setup is designed to _forward_ queries to an external resolving DNS server over TLS rather than act as a recursive DNS server, further negating the need for root-hints.

https://wiki.archlinux.org/index.php/unbound#Root_hints

https://nlnetlabs.nl/documentation/unbound/unbound-anchor/

**Comment by txtsd** [comment]
Gotcha!

**Comment by MatthewVance** [comment]
No worries. It is confusing. You're not the first to ask.
