### ISSUE TITLE
`dnssec_return_status: GETDNS_EXTENSION_TRUE` makes the setup fail

### ISSUE THREAD

**Issue by txtsd** [MatthewVance/stubby-docker#16]
Ok so I'm using the configs from your stubby and unbound on my Arch setup, and this line `dnssec_return_status: GETDNS_EXTENSION_TRUE` in stubby.yml makes the setup fail.

The services launch without an error, but all DNS lookups timeout.
Commenting that line out makes everything work as expected, and `drill` and `dig` both show DNSSEC is working.
What gives?

**Comment by MatthewVance** [comment]
Can you provide more details of how you're running this? If everything is set to the defaults and run per the README, DNS lookups should work. 

One possible issue could be the initial reliance on your LAN's default DNS to bootstrap initial connectivity. Perhaps that's blocking something or creating a timing issue. I've seen it be a bit pesky. If it's timing, running `docker-compose down` and `docker-compose up -d` may help. After stopping and re-starting, try dig/drill. 

Also, could you try https://github.com/MatthewVance/unbound-docker to see if it works on your setup?

**Comment by txtsd** [comment]
I'm not using Docker. I have stubby and unbound installed on the system, and I'm using the config files for them from this repo. Everything is the same except `syslog` is enabled for unbound, and I've had to turn off `dnssec_return_status` for stubby.

**Comment by MatthewVance** [comment]
When you get outside of Docker, it could be a number of things that are different that go beyond the configs. As I'm sure you know, most software has dependencies and OS dependencies. Docker allows those to be bundled together easier--this ability to ensure consistently between different runtimes is one of the big benefits of containers. 

Since your setup is not using Docker and not even being a Debian based distro, it is unsupported. 

You may want to take a look at https://dnsprivacy.org/wiki/display/DP/Configuring+Stubby#ConfiguringStubby-DNSSEC and https://github.com/getdnsapi/stubby/issues/184.
