### ISSUE TITLE
Unbound isn't able to start.

### ISSUE THREAD

**Issue by Sauron462** [MatthewVance/stubby-docker#18]
Hello, I was trying to setup this docker, but it says unbound is always restarting, with the log error "standard_init_linux.go:211: exec user process caused "no such file or directory".

**Comment by MatthewVance** [comment]
I'm sorry you're having trouble. Can you share more details about how
you're trying to run this? What commands are you using? Are you using a
docker-compose file? If so, what is it? Are you using all default configs?

**Comment by Sauron462** [comment]
I'm using the readme instructions to build and run the config, on another note, I don't entirely understand "point your DNS to the IP of your Docker host" however I am using default configs, aside from cleanbrowsing addresses enabled.

**Comment by MatthewVance** [comment]
Does this work if you pull the Docker images rather than build them
manually?

I suggest deleting the images you built. Instead, clone the repo. CD into
the directory and then run docker-compose up -d.

For the point to DNS, it means devices on your network will need to set
their OS DNS settings to the IP of the server running the Stubby. Its not
related to running or configuring Stubby itself.

**Comment by Sauron462** [comment]
Yep, pulling the images worked, and I believe I already have the DNS settings set up.
